name: NoMoreTNTChainCrash
version: '${version}'
main: uz.alex2276564.NoMoreTNTChainCrash
api-version: '1.16'
load: STARTUP
softdepend: [UltimateTNT, ExplodeAny, Tnttag, TNTModifier]
authors: [alex2276564]
description: Fix tnt chain crash (https://www.youtube.com/watch?v=HEet0raMR4o)
